apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
  namespace: gw
  labels:
    app: portal
spec:
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      labels:
        app: portal
    spec:
      nodeSelector:
        kubernetes.io/hostname: gateway
      containers:
        - name: portal
          image: docker.io/oven/bun:1.2-debian
          imagePullPolicy: IfNotPresent
          workingDir: /app
          command: ["sleep", "infinity"]
          envFrom:
            - configMapRef:
                name: portal-config
          ports:
            - name: http
              containerPort: 3001
          volumeMounts:
            - name: src-code
              mountPath: /app
          securityContext:
            privileged: true
      volumes:
        - name: src-code
          hostPath:
            path: /home/aisom/gateway-portal
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: portal
  namespace: gw
spec:
  selector:
    app: portal
  ports:
    - name: http
      port: 3001
      targetPort: http
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: portal-config
  namespace: gw
data:
  PUBLIC_APP_BASE_PATH: /
  PUBLIC_APP_BASE_PORT: "3001"
  ORIGIN: https://gw.aisom.cloud
  PUBLIC_APP_ORIGIN: https://gw.aisom.cloud
  API_BASE: https://gw.aisom.cloud/api/v1
  PUBLIC_KC_ISSUER_URI: https://gw.aisom.cloud/sso
  PUBLIC_KC_REALM: aisom
  PUBLIC_KC_CLIENT_FE_ID: fe
  AUTH_REFRESH_PATH: /auth/refreshToken
  AUTH_REFRESH_SKEW_SEC: "45"
  COOKIE_SECURE: "false"
