apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
  namespace: gateway
  labels:
    app: portal
spec:
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      labels:
        app: portal
    spec:
      nodeSelector:
        kubernetes.io/hostname: edgexpert-1c3b 
      containers:
        - name: portal
          image: docker.io/oven/bun:1.2-debian
          imagePullPolicy: IfNotPresent
          workingDir: /app
          command: ["sleep", "infinity"]
          envFrom:
            - configMapRef:
                name: portal-config
          ports:
            - name: http
              containerPort: 3001
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
          volumeMounts:
            - name: src-code
              mountPath: /app
          securityContext:
            privileged: true
      volumes:
        - name: src-code
          hostPath:
            path: /home/aisom/portal
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: portal
  namespace: gateway
spec:
  selector:
    app: portal
  ports:
    - name: http
      port: 3001
      targetPort: http
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: portal-config
  namespace: gateway
data:
  PUBLIC_APP_BASE_PATH: /aisom
  PUBLIC_APP_BASE_PORT: "3001"
  API_BASE: http://kapi.gateway:3001/api/v1
  PUBLIC_KC_ISSUER_URI: https://gateway.aisom.cloud/sso
  PUBLIC_KC_REALM: aisom
  PUBLIC_KC_CLIENT_FE_ID: fe
  AUTH_REFRESH_PATH: /auth/refreshToken
  AUTH_REFRESH_SKEW_SEC: "45"
  COOKIE_SECURE: "false"
